Update mounted file paths and add warning to use Fedora as default VM Template
freedomofpress/securedrop-workstation-docs pull request #131
Opened 2023-03-24 17:48 UTC by nathandyer

This PR changes the path of the mounted Persistent storage drives used to copy keys and configurations from existing SVS and Journalist Workstations.

This also adds a warning to use Fedora as the default VM template, rather than Debian (I learned this one the hard way).

## Testing:
- [ ] CI passes 
- [ ] `make linkcheck` passes locally
- [ ] Visual check on local build
- [ ] [Bonus points] Plugging in an Admin (or Journalist) Workstation drive to a Qubes 4.1.2 system, opening the Vault Qube, and verifying that the mount point is now `/media` rather than `/run/media` after entering the passphrase.

2023-07-01 00:08 UTC, legoktm requested changes

2023-07-01 00:08 UTC, legoktm commented on docs/admin/install.rst
> +.. warning:: Make sure **Fedora** is selected as the default VM template. Otherwise, you will need to manually switch the *Work* Qube template to Fedora in order to download the SecureDrop Workstatio
Does this need to be a warning vs just a bullet below that says "default VM template: Fedora" (idk what it looks like actually)? I'm thinking that just letting people follow the instructions will be easier than giving them a warning here...

2023-07-01 00:08 UTC, legoktm commented on docs/admin/install.rst
> -      "gpg --homedir /run/media/user/TailsData/gnupg -K --fingerprint"
I plugged my Admin Workstation drive into a Fedora 37 VM and it mounted in `/run/media/...` (the old paths). Do I need to do something different? When did the paths change?

2023-07-26 13:54 UTC, nathandyer commented
Closing this PR for now, the path change ended up being related to the mistake I made in changing the default template. And after reviewing our documentation again, I think it's already clear that users should just go with defaults. Not sure why I decided to venture off the beaten path during this reinstall session. Sometimes a little knowledge is a dangerous thing :) 

I have since re-installed a couple times, and the current instructions are still valid.

2023-07-26 13:54 UTC, closed without merging