Update backup/restore docs note about custom templates
freedomofpress/securedrop-workstation-docs pull request #253
Opened 2024-07-23 18:50 UTC by rocodes

Include our recommended path for custom template upgrades (rebuild instead of upgrade). Link to upstream dist-upgrade template-standalone-upgrade instructions.

2024-07-31 22:47 UTC, eloquence requested changes
(A couple of nits)

2024-07-31 22:47 UTC, eloquence commented on docs/admin/reference/backup.rst
> +  then upgrade their package repositories to the Qubes 4.2 repoistories using
typo: `repoistories`

2024-07-31 22:47 UTC, eloquence commented on docs/admin/reference/backup.rst
> +  ``qubes-dist-upgrade --template-standalone--upgrade`` (more information can be
It looks like this tool has to be installed first with `sudo qubes-dom0-update -y qubes-dist-upgrade` -- on my system it was not present, and the linked docs instruct the user to install it, but we should probably say so here as well.

Typo: `--template-standalone--upgrade` (double hyphen)

2024-10-17 17:41 UTC, zenmonkeykstop commented
Will apply fixes and update.

2024-10-29 23:46 UTC, eloquence approved these changes
LGTM.

2024-10-29 23:50 UTC, merged